backSide=
{AFG: {passport: false},
 AGO: {passport: false},
 AIA: {passport: false},
 ALB: {passport: false, driving_license: false, national_identity_card: true},
 AND: {passport: false, driving_license: false},
 ARE: {passport: false, driving_license: false, national_identity_card: true},
 ARG: {passport: false, driving_license: false, national_identity_card: true},
 ARM: {passport: false},
 ATG: {passport: false},
 AUS: {passport: false, driving_license: false},
 AUT: {national_identity_card: true},
 AZE: {passport: false, driving_license: false, national_identity_card: true},
 BDI: {passport: false},
 BEL: {national_identity_card: true},
 BEN: {passport: false},
 BFA: {passport: false},
 BGD: {passport: false, driving_license: false, national_identity_card: true},
 BGR: {national_identity_card: true},
 BHR: {passport: false, national_identity_card: true},
 BHS: {passport: false, driving_license: false},
 BIH: {passport: false, driving_license: false, national_identity_card: true},
 BLR: {passport: false, driving_license: false},
 BLZ: {passport: false},
 BMU: {passport: false, driving_license: false},
 BOL: {passport: false, driving_license: false, national_identity_card: true},
 BRA: {national_identity_card: true},
 BRB: {passport: false, driving_license: false},
 BRN: {passport: false, national_identity_card: true},
 BTN: {passport: false},
 BWA: {passport: false},
 CAF: {passport: false},
 CAN: {passport: false, driving_license: false, national_identity_card: true},
 CHE: {passport: false, driving_license: false, national_identity_card: true},
 CHL: {passport: false, driving_license: false, national_identity_card: true},
 CHN: {passport: false, national_identity_card: true},
 CIV: {passport: false, driving_license: false, national_identity_card: true},
 CMR: {passport: false},
 COD: {passport: false},
 COG: {passport: false},
 COL: {passport: false, driving_license: false, national_identity_card: true},
 COM: {passport: false},
 CPV: {passport: false},
 CRI: {passport: false, driving_license: true, national_identity_card: true},
 CUB: {passport: false},
 CYM: {passport: false},
 CYP: {national_identity_card: true},
 CZE: {national_identity_card: true},
 DEU: {national_identity_card: true},
 DJI: {passport: false},
 DMA: {passport: false},
 DNK: {passport: false, driving_license: false, residency_permit: true},
 DOM: {passport: false, driving_license: false, national_identity_card: true},
 DZA: {passport: false, national_identity_card: true},
 ECU: {passport: false, driving_license: false, national_identity_card: true},
 EGY: {passport: false, driving_license: false},
 ERI: {passport: false},
 ESP: {national_identity_card: true},
 EST: {national_identity_card: true},
 ETH: {passport: false, national_identity_card: true},
 FIN: {national_identity_card: true},
 FJI: {passport: false, driving_license: false},
 FRA: {national_identity_card: true},
 FRO: {passport: false, driving_license: false},
 FSM: {passport: false},
 GAB: {passport: false},
 GBR: {passport: false, driving_license: false, residency_permit: false, naturalisation_certificate: false, home_office_letter: false, immigration_status_document: false, birth_certificate: false},
 GEO: {passport: false, driving_license: false, national_identity_card: true},
 GGY: {passport: false, driving_license: false},
 GHA: {passport: false, driving_license: false, national_identity_card: true},
 GIB: {passport: false, driving_license: false, national_identity_card: true},
 GIN: {passport: false},
 GMB: {passport: false},
 GNB: {passport: false},
 GNQ: {passport: false},
 GRC: {national_identity_card: true},
 GRD: {passport: false},
 GTM: {passport: false, driving_license: true, national_identity_card: true},
 GUY: {passport: false},
 HKG: {passport: false, driving_license: false, national_identity_card: true},
 HND: {passport: false},
 HRV: {passport: false, driving_license: false, national_identity_card: true},
 HTI: {passport: false},
 HUN: {national_identity_card: true},
 IDN: {passport: false, driving_license: false, national_identity_card: true},
 IMN: {passport: false, driving_license: false},
 IND: {national_identity_card: true},
 IRL: {passport: false, passport_card: true, driving_license: false, residency_permit: true},
 IRN: {passport: false},
 IRQ: {passport: false},
 ISL: {national_identity_card: true},
 ISR: {passport: false, driving_license: false},
 ITA: {national_identity_card: true},
 JAM: {passport: false, driving_license: false},
 JEY: {passport: false, driving_license: false},
 JOR: {passport: false, driving_license: false, national_identity_card: true},
 JPN: {passport: false, driving_license: false, residency_permit: false},
 KAZ: {passport: false},
 KEN: {passport: false, national_identity_card: true},
 KGZ: {passport: false},
 KHM: {passport: false},
 KIR: {passport: false},
 KNA: {passport: false},
 KOR: {passport: false},
 KWT: {passport: false, driving_license: false, national_identity_card: true},
 LAO: {passport: false},
 LBN: {passport: false},
 LBR: {passport: false},
 LBY: {passport: false},
 LCA: {passport: false},
 LIE: {national_identity_card: true},
 LKA: {passport: false, driving_license: false},
 LSO: {passport: false},
 LTU: {national_identity_card: true},
 LUX: {national_identity_card: true},
 LVA: {national_identity_card: true},
 MAC: {residency_permit: false},
 MAF: {driving_license: false},
 MAR: {passport: false, driving_license: false, national_identity_card: true},
 MCO: {passport: false, national_identity_card: true},
 MDA: {passport: false, driving_license: false, national_identity_card: true},
 MDG: {passport: false},
 MDV: {passport: false},
 MEX: {passport: false, driving_license: false, voter_id: false, work_permit:false},
 MHL: {passport: false},
 MKD: {passport: false, driving_license: false, national_identity_card: true},
 MLI: {passport: false},
 MLT: {national_identity_card: true},
 MMR: {passport: false},
 MNE: {passport: false, driving_license: false, national_identity_card: true},
 MNG: {passport: false, driving_license: false},
 MOZ: {passport: false},
 MRT: {passport: false},
 MSR: {passport: false},
 MUS: {passport: false},
 MWI: {passport: false},
 MYS: {passport: false, driving_license: false, national_identity_card: true},
 NAM: {passport: false},
 NER: {passport: false},
 NGA: {passport: false, driving_license: false, national_identity_card: true},
 NIC: {passport: false},
 NLD: {national_identity_card: true},
 NOR: {passport: false, driving_license: false, residency_permit: true},
 NPL: {passport: false},
 NRU: {passport: false},
 NZL: {passport: false, driving_license: false},
 OMN: {passport: false, driving_license: false, national_identity_card: true},
 PAK: {passport: false, national_identity_card: true},
 PAN: {passport: false},
 PER: {passport: false, driving_license: false, national_identity_card: true},
 PHL: {passport: false, driving_license: false, national_identity_card: true},
 PLW: {passport: false},
 PNG: {passport: false},
 POL: {national_identity_card: true},
 PRI: {passport: false, driving_license: false, national_identity_card: true},
 PRK: {passport: false},
 PRT: {national_identity_card: true},
 PRY: {passport: false, driving_license: false, national_identity_card: true},
 PSE: {passport: false},
 QAT: {passport: false, driving_license: false, national_identity_card: true},
 ROU: {national_identity_card: true},
 RUS: {passport: false, driving_license: false},
 RWA: {passport: false},
 SAU: {passport: false, driving_license: false, residency_permit: false},
 SDN: {passport: false},
 SEN: {passport: false, national_identity_card: true},
 SGP: {passport: false, driving_license: false, national_identity_card: true},
 SLB: {passport: false},
 SLE: {passport: false},
 SLV: {passport: false},
 SMR: {passport: false},
 SOM: {passport: false},
 SRB: {passport: false, driving_license: false, national_identity_card: true},
 SSD: {passport: false},
 STP: {passport: false},
 SUR: {passport: false},
 SVK: {driving_license: false, passport: false, national_identity_card: true},
 SVN: {national_identity_card: true},
 SWE: {national_identity_card: true},
 SWZ: {passport: false},
 SYC: {passport: false},
 SYR: {passport: false},
 TCA: {passport: false},
 TCD: {passport: false},
 TGO: {passport: false},
 THA: {passport: false, driving_license: false, national_identity_card: true},
 TJK: {passport: false},
 TKM: {passport: false},
 TLS: {passport: false},
 TON: {passport: false},
 TTO: {passport: false, driving_license: false, national_identity_card: true},
 TUN: {passport: false, driving_license: false},
 TUR: {passport: false, driving_license: false, national_identity_card: true},
 TUV: {passport: false},
 TWN: {passport: false, national_identity_card: true},
 TZA: {passport: false, driving_license: false, voter_id: false},
 UGA: {passport: false, driving_license: false, national_identity_card: true},
 UKR: {passport: false, driving_license: false, national_identity_card: true},
 UNK: {passport: false, national_identity_card: true},
 URY: {passport: false, driving_license: false, national_identity_card: true},
 USA: {passport: false, driving_license: false, national_identity_card: true},
 UZB: {passport: false},
 VEN: {passport: false, national_identity_card: true},
 VNM: {passport: false, driving_license: false, national_identity_card: true},
 VUT: {passport: false},
 WSM: {passport: false},
 XPO: {passport: false},
 YEM: {passport: false, driving_license: false},
 ZAF: {passport: false, driving_license: false, national_identity_card: true},
 ZMB: {passport: false},
 ZWE: {passport: false}
}; // backSide
module.exports={backSide};
