language: node_js
node_js:
- 10.8.0
os: linux
dist: xenial
services:
- mongodb
before_script:
  # - echo "replSet = myReplSetName" | sudo tee -a /etc/mongodb.conf
  # - sudo service mongod restart
  # - sleep 20
  # - mongo --eval 'rs.initiate()'
  # - sleep 15
  - sleep 10
  - mongoimport --jsonArray --db worbli --collection identity_documents --file documents.json
addons:
  hosts:
    - portalbackend-mongo
script:
- npm run test
before_install:
# encode with:
#  export ENV_PASS=yOuR_PasS
#  openssl enc -e -aes-256-cbc -md md5 -salt -pass env:ENV_PASS -in .env -out env.encoded
# see https://askubuntu.com/questions/1067762/unable-to-decrypt-text-files-with-openssl-on-ubuntu-18-04
- openssl aes-256-cbc -d -pass pass:${ENV_PASS} -in .env.enc -out .env
env:
  global:
    - IMAGE_NAME=portalbackend
    - DEPLOY_BRANCHES=develop_v3 uat_v3
    - AWS_REGION=us-east-1
deploy:
  skip_cleanup: true
  provider: script
  script:
    - ./bin/run.sh
  on:
    all_branches: true

# deploy:
# - provider: s3
#   access_key_id: $TRAVIS_AWS_ACCESS_KEY_ID
#   secret_access_key: $TRAVIS_AWS_SECRET_ACCESS_KEY
#   local_dir: dpl_cd_upload
#   key: latest.zip
#   bundle_type: zip
#   skip_cleanup: true
#   on: 
#     repo: worbli/portalBackEnd
#     branch: develop_v3
#   bucket: $TRAVIS_S3_DEV_API_BUCKET_NAME
#   region: us-west-2
# - provider: codedeploy
#   access_key_id: $TRAVIS_AWS_ACCESS_KEY_ID
#   secret_access_key: $TRAVIS_AWS_SECRET_ACCESS_KEY
#   bucket: $TRAVIS_S3_DEV_API_BUCKET_NAME
#   key: latest.zip
#   bundle_type: zip
#   application: $AWS_CODE_DEPLOY_APPLICATION
#   deployment_group: $AWS_CODE_DEPLOY_DEPLOYMENT_GROUP
#   on:
#     repo: worbli/portalBackEnd
#     branch: develop_v3
#   region: us-west-2
#   wait_until_deployed: true
# - provider: s3
#   access_key_id: $TRAVIS_AWS_ACCESS_KEY_ID
#   secret_access_key: $TRAVIS_AWS_SECRET_ACCESS_KEY
#   bucket: $TRAVIS_S3_UAT_API_BUCKET_NAME
#   local_dir: dpl_cd_upload
#   key: latest.zip
#   bundle_type: zip
#   skip_cleanup: true
#   on: 
#     repo: worbli/portalBackEnd
#     branch: uat_v3
#   region: us-west-2
# - provider: codedeploy
#   access_key_id: $TRAVIS_AWS_ACCESS_KEY_ID
#   secret_access_key: $TRAVIS_AWS_SECRET_ACCESS_KEY
#   bucket: $TRAVIS_S3_UAT_API_BUCKET_NAME
#   key: latest.zip
#   bundle_type: zip
#   application: $AWS_CODE_DEPLOY_APPLICATION
#   deployment_group: $AWS_UAT_CODE_DEPLOY_DEPLOYMENT_GROUP
#   on:
#     repo: worbli/portalBackEnd
#     branch: uat_v3
#   region: us-west-2
#   wait_until_deployed: true
# before_deploy:
#   - rm -fr node_modules
#   - shopt -s dotglob && zip -rq latest *
#   - mkdir -p dpl_cd_upload
#   - mv latest.zip dpl_cd_upload/latest.zip

notifications:
  slack:
    secure: "dkYYe0i/MLCxOeA/OmSlvxJ0n9BEYJIWE6JK872JQOEvM9jzZoD5v/8z2PyszRhYh47spqxatWa5YOiCt/xevFBKCQgYhn1tS+aa4TuDfBOachod+K5VOhWxE8iuhxG/BmbUkjeeT42FQffZQ4QFWFZOHCqFreauCIQ8wZayG+uQWK+AX3Z8SCW0JX863ooWVLLcS8NTvttIhdlWw+hG8pvTYuuNk07aLAp/ytugSCih/oBm/JyGX9j7Y3H4MLtEQaux8+s1eC4EPsQqMKHc6UZDRAbtiXvqIzGixR7a+ZXILTz6YEg26CWpBXD05erpL/Y3CVTNFYA+ErWGSM0ZFHUbF/xZpQCXJetwrtCj9eT9feUPiUuD07LkBr+5tqIqQxSFvWiHHJ8TiPTYYHF2yn4K4POsXs9m8YYuAl+96WDqh9ZfbB1A2w7vMG63+7PZOgmjkzb7IG/X7XJe6ramX4eXA02P4NGYKEdQpZMtZpYBUiRpqmwMU60WqDQAmOgKvqKfXS3ceC4cQ47WJllJy25cdo7knyBTRgdr9tdepqz3GT7OS2rdbUPd561sjSK8hdUeAB7st30OHo3Q5cJJKpKUKo5eIP5mXfkNdrp1t6DJdtjpU2zTO7A8r4hZx96ZphMxQcJKPkE4ZCjzhtdYbmnu1ZhpM+lVaaeBTeLDtyU="
