version: "3"

services:

  portalbackend:
    ports:
      - '9229:9229'
      - '5000:5000'
    environment:
      NODE_ENV: development
    command:
      bash -c "npm install && npm run dev"
      # bash -c "npm run import"
      # bash -c "npm run test"
