version: "3"

services:

  portalbackend:
    image: node:10
    container_name: portalbackend
    restart: always
    volumes:
      - .:/usr/src/app
    # ports:
    #   - '9020:9020'
    # environment:
      # API_PORT: 9020
    working_dir: /usr/src/app

  portalbackend-nginx:
    image: nginx
    container_name: portalbackend-nginx
    restart: always
    links:
      - portalbackend
    ports:
      - 9020:80
      - 80:80
    volumes:
      - ./conf:/etc/nginx/conf.d
